// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IMJb1AC-gpKeYLReke6F427QIFrke9o',
    appId: '1:409434141367:web:daa055488ffad95c411332',
    messagingSenderId: '409434141367',
    projectId: 'quran-16c57',
    authDomain: 'quran-16c57.firebaseapp.com',
    storageBucket: 'quran-16c57.firebasestorage.app',
    measurementId: 'G-HXSWEPRE6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBhfbhvHa1532BfsxU9Yge8crGAUtJGQ',
    appId: '1:409434141367:android:36bdf9f74defaf2d411332',
    messagingSenderId: '409434141367',
    projectId: 'quran-16c57',
    storageBucket: 'quran-16c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoe0R24gpBzRZRiclQYxdW6ApEUUhYZpQ',
    appId: '1:409434141367:ios:18642c0e5dc4136e411332',
    messagingSenderId: '409434141367',
    projectId: 'quran-16c57',
    storageBucket: 'quran-16c57.firebasestorage.app',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoe0R24gpBzRZRiclQYxdW6ApEUUhYZpQ',
    appId: '1:409434141367:ios:18642c0e5dc4136e411332',
    messagingSenderId: '409434141367',
    projectId: 'quran-16c57',
    storageBucket: 'quran-16c57.firebasestorage.app',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-IMJb1AC-gpKeYLReke6F427QIFrke9o',
    appId: '1:409434141367:web:747ba16b06cb048b411332',
    messagingSenderId: '409434141367',
    projectId: 'quran-16c57',
    authDomain: 'quran-16c57.firebaseapp.com',
    storageBucket: 'quran-16c57.firebasestorage.app',
    measurementId: 'G-MN6WZRQKYT',
  );
}
